console.log('1 - Para que serve o método Scrum?');
console.log('2 -Como funciona o método Scrum?');
console.log('3 - O que é Git?');
console.log('4 - O que é um scrum Product Owner?');
console.log('5 - Qual o comando para criação de um novo repositório no Git?');
console.log('6 - O que é o HTTP?');
console.log('7 - Como funciona o HTTP?');
console.log('8 - Com o Git Você pode propor mudanças (adicioná-las ao Index) usando um comando. Qual é esse comando?');
console.log('9 - O que é a Branch master e para que serve?');
console.log('10 - Quais são os comandos usados para atualizar um repositório local e fazer merge de um outro branch ao seu branch ativo?');
console.log('11 - Qual a diferença entre git e github?');
console.log('12 - Quais os dois verbos http que podemos utilizar para realizar um update? Explique a diferença entre eles.');
console.log('13 - Qual o status code que pode ser usado na criação de um novo usuário?');
console.log('14 - Quais são os três status code que modem ser utilizados para realizar o delete?');
console.log('15 - Exemplifique para que serve os metódos http 1xx, 2xx, 3xx, 4xx e 5xx. De uma forma macro (geral)!');
console.log('16 - Conta pra gente como foi sua experiência na Sprint#01 do programa de bolsa @node.js_mar22 e quais suas expectativas a partir de agora:');